add reference gain design pattern to create_statefbk_iosystem
python-control/python-control pull request #1071
Opened 2024-12-02 06:20 UTC by murrayrm

This PR adds a second design pattern to the `create_statefbk_iosystem` function, allowing controllers that use a static gain on the reference input instead of the desired state and input.  As described in the user documentation:

> The `~control.create_statefbk_iosystem` function can be used to create an I/O system consisting of a state feedback gain (with optional integral action and gain scheduling) and an estimator.  A basic state feedback controller of the form
>
> $u = u_d - K (x - x_\text{d})$
>
> can be created with the command::
>
>    ctrl, clsys = ct.create_statefbk_iosystem(sys, K)
> 
> where `sys` is the process dynamics and `K` is the state feedback gain (e.g., from LQR).  The function returns the controller `ctrl` and the closed loop systems `clsys`, both as I/O systems.  The input to the controller is the vector of desired states $x_\text{d}$, desired inputs $u_\text{d}$, and system states $x$.
>
> The above design pattern is referred to as the "trajectory generation" ('trajgen') pattern, since it assumes that the input to the controller is a feasible trajectory $(x_\text{d}, u_\text{d})$.  Alternatively, a controller using the "reference gain" pattern can be created, which implements a state feedback controller of the form
>
>  $u = k_\text{f}\, r - K x$,
>
> where $r$ is the reference input and $k_\text{f}$ is the feedforward gain (normally chosen so that the steady state output $y_\text{ss}$ will be equal to $r$).
>
> A reference gain controller can be created with the command::
> 
>     ctrl, clsys = ct.create_statefbk_iosystem(sys, K, kf, feedfwd_pattern='refgain')
>
> The reference gain design pattern is described in more detail in Section 7.2 of FBS2e (Stabilization by State Feedback) and the trajectory generation design pattern is described in Section 8.5 (State Space Controller Design).

2024-12-04 20:34 UTC, slivingston commented
I will review this today.

2024-12-05 03:08 UTC, slivingston requested changes

2024-12-05 03:08 UTC, slivingston commented on control/tests/statefbk_test.py
> +            sys, K, Kf, feedfwd_pattern='refgain')
Related to the above, there may be existing code that calls create_statefbk_iosystem() with 3 positional arguments, thus giving `integral_action` without using the keyword. With this PR, that would effectively be a call to create_statefbk_iosystem() with a value to `feedfwd_gain` but `feedfwd_pattern` still at its default. I modified the test [test_lqr_integral_continuous](https://github.com/python-control/python-control/blob/12dda4e3e75be69b172be0eb340e2eedf82b3ef4/control/tests/statefbk_test.py#L761) to demonstrate this case, and the resulting error is
```
        if isinstance(gain, np.ndarray):
            K = gain
            if K.shape != (sys_ninputs, estimator.noutputs + nintegrators):
>               raise ControlArgument(
                    f'control gain must be an array of size {sys_ninputs}'
                    f' x {sys_nstates}' +
                    (f'+{nintegrators}' if nintegrators > 0 else ''))
E               control.exception.ControlArgument: control gain must be an array of size 2 x 4

control/statefbk.py:831: ControlArgument
```
It is good that an exception is raised, but users may be confused about the cause.

I think that having `feedfwd_gain` as the third parameter is intuitive and worth keeping, so I propose that a `ControlArgument` exception is raised if `feedfwd_gain` is not `None` but `feedfwd_pattern != 'refgain'`.

2024-12-07 04:56 UTC, murrayrm commented on control/tests/statefbk_test.py
> +            sys, K, Kf, feedfwd_pattern='refgain')
I've left the single function for now, though I agree this function is getting big and complicated.  I'm not sure that splitting it in two simplifies things much, and the current naming matches the `create_estimator_iosystem` and `create_mpc_iosystem` naming pattern (and functionality).

I created the exception suggested above + unit test.

2024-12-07 06:59 UTC, slivingston approved these changes

2024-12-07 15:52 UTC, merged