Enable scalar division of state-space objects
python-control/python-control pull request #811
Opened 2022-12-10 10:17 UTC by roryyorke

I think this is a reasonable if minor improvement; it lets one write `gscaled = g / 2` instead of `gscaled = g * (1/2)`.  I'm less sure about division by arrays, but I see multiplication by arrays is allowed, and it seems natural to have symmetry between these operations.

I added a simple test for `StateSpace / scalar` and `StateSpace / array`, but not for `InputOutputSystem / scalar`. etc.

I also modified the type-conversion tests as required.

2022-12-11 17:22 UTC, murrayrm reviewed
LGTM.

2022-12-12 16:54 UTC, sawyerbfuller commented on control/iosys.py
> +        """Multiply two input/output systems (series interconnection)"""
should this docstring say "divide"?

2022-12-12 17:01 UTC, sawyerbfuller requested changes
looks good to me - with one possible update in a docstrong

2022-12-13 03:38 UTC, roryyorke commented
Whoops, yes. Should be similar to StateSpace truediv docstring. Earliest I
can look at this is Friday.

On Mon, 12 Dec 2022, 18:55 Sawyer Fuller, ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In control/iosys.py
> <https://github.com/python-control/python-control/pull/811#discussion_r1046096197>
> :
>
> > @@ -346,6 +346,17 @@ def __neg__(sys):
>          # Return the newly created system
>          return newsys
>
> +    def __truediv__(sys2, sys1):
> +        """Multiply two input/output systems (series interconnection)"""
>
> should this docstring say "divide"?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/python-control/python-control/pull/811#pullrequestreview-1213950009>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAA3C7TWMZLIXFWKP4YPHCDWM5KGRANCNFSM6AAAAAAS2FXV4E>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-12-16 05:08 UTC, merged